// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"todo-code-gen/internal/config"
	"todo-code-gen/internal/server/mysql"
	"todo-code-gen/internal/todo/boundary"
	"todo-code-gen/internal/todo/control"
	"todo-code-gen/internal/todo/entity"
)

// Injectors from wire.go:

func Initialize() *AppContext {
	databaseConfig := config.NewDatabaseConfig()
	queries := mysql.ProvideDatabase(databaseConfig)
	repository := entity.ProvideRepository(queries)
	todoControllerImpl := control.ProvideController(repository)
	todoRouter := boundary.ProvideRouter(todoControllerImpl)
	appContext := &AppContext{
		TodoRouter: todoRouter,
	}
	return appContext
}

// wire.go:

type AppContext struct {
	*boundary.TodoRouter
}
